server/app.js, server/config.example.js
environmental dependent config pattern added to config.example.js to copy into local config.js
=> (feat) Added pattern for config.js to config.example.js

package.json, test/serverSpec.js
Add a few dev dependencies for pretty output from our test suite.
=> Test/create Pretty Print

contract.js
=> Update contract file. Closes #9

server/components/group/groupController.js, server/components/group/index.js, server/components/heart/heartController.js, server/components/heart/index.js, server/routes/groupRouter.js, server/routes/index.js
Also add empty files for heart and flag controllers and indexes
=> (Feat)Add Group Router closes #43

server/components/user/userController.js, test/userServerSpec.js
fixed testing - only touched userControllerSpec
=> (feat)add tests

gulpfile.js, package.json, test/serverSetup.js
Also added testing server requests by using promises in our request module.
=> Add slightly more robust testing to serverSetup.js

server/components/user/userController.js, test/testHelpers.js, test/userServerSpec.js
abstract put and post testing so we can test other models
=> (feat)add test helper functions for post and put

server/app.js, server/components/user/passport.js, server/components/user/userModel.js, server/routes/authRouter.js
- Sets up routes to authenticate using Google OAuth.
- Updates the User database schema to make the 'name' field no longer required to be unique.
=> (feat) auth: Implements Google OAuth2 support.

package.json, server/components/user/passport.js
- Implements Facebook OAuth support.
- Updates Google OAuth to update an existing user profile if the email is already in the database.
=> (feat) auth: Implements Facebook OAuth support

server/components/user/addDummyUser.js, server/components/user/userController.js, server/config.example.js, server/routes/dummyDataRouter.js, server/routes/userRouter.js, test/userServerSpec.js
=> (Feat) user router

extension/chrome/comment.css, extension/chrome/comment.js, extension/chrome/config.json, extension/chrome/options.html, extension/chrome/options.js, extension/chrome/popup.html, extension/chrome/popup.js, extension/chrome/rust.js, server/routes/dummyDataRouter.js
implements comment posting and auth checking, appends new comments.
=> feat/extension-chrome > implements comment posting and auth checking

server/components/user/passport.js
Parallels fixes for Google OAuth.
=> Fixes promise fallthrough on Facebook OAuth.

extension/chrome/rust.js, package.json, server/middleware/isAuthorized.js, server/middleware/isLoggedIn.js, server/routes/commentRouter.js, server/routes/dummyDataRouter.js, server/routes/errorRouter.js
adds input field sanitation and login validation posting comments with error response for json request types & redirect for all other request types
=> feat/sanitize - adds input field sanitation and login validation

client/App.js, client/components/Comment.js, client/components/Navigation.js, client/components/Profile.js, server/components/comment/commentController.js, server/routes/commentRouter.js
- Adds a starting Comment component that should be usable for all comment feeds.
- Adds a new comment route (/api/comments/get/user) to load all comments for a user (currently just the logged in user)
=> (feat) webapp: begins to build out user profile

client/components/Comment.js, client/components/Profile.js, contract.js
Updates contract and Comment component to reference correct fields; Profile creates Comments in render.
=> (feat) webapp: Updates contract and Comment component to use actual fields returned by comment api.

client/components/Website.js, server/components/user/passport.js, server/components/user/userModel.js
Also removes unique index on User name field.
=> (bug) auth: fixes error in passport query to find whether a user is existing

server/components/url/urlController.js, server/components/url/urlModel.js, server/utils/parseURL.js
=> Feat/ add host to db

client/index.html, client/test/oxidizer.js, server/components/comment/commentController.js, server/components/flag/flagController.js, server/components/heart/heartController.js
Clicking the fav or flag button again removes it from a particular comment. This now acts as a toggle.
=> Feat/favs: Users limited to 1 fav and 1 flag per comment

client/test/oxidizer.js, server/components/comment/commentController.js, server/components/flag/flagController.js, server/components/heart/heartController.js, server/components/url/urlController.js, server/routes/commentRouter.js, server/routes/urlRouter.js
=> Feat/ heartedByUser flaggedByUser

client/components/Comment.js, client/components/Profile.js, contract.js, server/components/comment/commentController.js, server/routes/commentRouter.js
- Also updates comment API routes to support Profile component.
=> (feat) profile: additions to Profile component

client/components/Profile.js, contract.js, server/components/comment/commentController.js, server/routes/commentRouter.js
- Comment Router: /api/comments/get - some refactoring, fixes for url and text searching.
- Profile component: refactoring for Comment API + begins to make changes to support scrolling.
=> (feat) profile: updates for changes in Comment API

client/components/Profile.js, package.json, server/components/comment/commentController.js, server/routes/commentRouter.js
Also cleans up some functions; updates Comment API to handle lastUpdateId correctly.
=> (feat) profile: Implements scrolling to load more comments in Profile

.gitignore, server/app.js
=> adds new relic application monitoring

package.json, server/app.js
=> (feat/redis) adds redis session store for express and passport in deployment

extension/chrome/background.js, extension/chrome/lib/css/sideframe.css, extension/chrome/lib/js/popup.js, extension/chrome/sideframe.html, extension/chrome/sideframe.js, server/routes/commentRouter.js
- Also fixes some typos reading in values from the Chrome store into in-memory settings.
=> (feat) extension: Adds support for public vs. private commenting and comment feeds

client/components/Profile.js
Also adds link to reload comments without search terms.
=> (feat) client: Adds dropdown to switch between seeing public or private comments

client/components/Website.js, server/components/comment/commentController.js, server/components/url/urlController.js, server/components/url/urlModel.js, server/components/user/userController.js, server/routes/commentRouter.js, server/routes/urlRouter.js, server/routes/userRouter.js
replyCount and heartCount returns, notifications sent on comment/get route
=> Featreply count

client/components/Profile.js, contract.js, package.json, server/components/heart/heartModel.js, server/routes/commentRouter.js
Includes support to autoload additional comments with scrolling.
=> (feat) profile: allow user to load their favorited comments

client/App.js, client/components/Profile.js, contract.js, server/routes/commentRouter.js
Loading of other users is via a url parameter with the userId of the user to check out.
=> Implements support for loading a user profile that is not that of the logged in user

extension/chrome/lib/css/sideframe.css, extension/chrome/sideframe.html
This should be replaced by a server side method down the line!
=> Feat/extension2 - adds client side hiding of comments flagged by user

client/components/Comment.js, client/components/Profile.js, server/routes/commentRouter.js
- Also changes the response code from 200 to 500 if there is an error deleting a comment.
=> Adds ability to delete a comment when on logged in user's profile.

client/test/admin_actions.js, extension/chrome/sideframe.html, extension/chrome/sideframe.js
Also prevents users from submitting content with nothing in it.
=> Feat/ChromeComments - Link dropdown menus in Extension.

client/components/Navigation.js, server/components/comment/commentController.js, server/components/comment/commentModel.js, server/components/comment/getComments.js, server/components/heart/heartController.js, server/components/heart/heartModel.js, server/components/user/getUserInfo.js, server/components/user/userController.js, server/routes/commentRouter.js, server/routes/index.js
added url parsing for correct posting to db, returns correct username
=> (bug) comments query cleanup

client/components/Profile.js
- userInfo is now an array instead of an object for /api/comments
=> Updates to work with refactored route return values

client/App.js, client/components/Comment.js, client/components/Leaderboard.js, client/components/Navigation.js, client/components/Profile.js
=> Implements basic leaderboard that loads most favorited comments first

client/components/Comment.js, client/components/Leaderboard.js, server/components/comment/commentController.js, server/components/comment/getComments.js
v.s. 'oldest comment id' to determine which top comments to load on sequential requests.
=> Updates query and Leaderboard component to pass an offset

extension/chrome/sideframe.html, extension/chrome/sideframe.js
- via dropdown selector in menu.
- Also closes issue #269 -- fixes field referenced if user hearted a comment.
=> (feat) extension: adds ability to sort via date or popularity

server/components/user/getUserInfo.js, server/routes/index.js
Amended commit to fix this didn't get pushed up to the previous pull request.
=> Fixes stale references to dummyDataRouter.
